### ISSUE TITLE
Point to WCAG-EM Report Tool

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-eval-report-templates#11]
Since this still isn't updated and may not be for a while. we should probably add a clear pointer to WCAG-EM report tool - or the resulting as a template?

**Comment by remibetin** [comment]
Resolved by https://github.com/w3c/wai-eval-report-templates/commit/1cf292c59c8c002f41587f41bbcb939a8e3f1607

I am closing this issue.
