### ISSUE TITLE
WACAG EM-Report tool report template

### ISSUE THREAD

**Issue by yatil** [w3c/wai-eval-report-templates#2]
From @nitedog via email:

> Just one quick thought, how about providing the template as a separate (downloadable) file? I think you could simply download an empty report from the WCAG-EM Report Tool, and annotate it with the same text you have now. The current page would be just an explainer - basically the first paragraph you have now and maybe some high-level thoughts on the important parts of a template.
>
> Just a thought, maybe for group discussion if needed.

**Comment by dboudreau** [comment]
I do agree that a downloadable file provided in the document would be a nice touch.

**Comment by remibetin** [comment]
I am closing this issue that seems resolved by https://github.com/w3c/wai-eval-report-templates/commit/7019fc7a139940c16d6fb9c9d2059082c1d4dbb7

Shawn added a link to an empty report from the WCAG-EM Report Tool, that includes links to download the report in HTML or JSON.
