### ISSUE TITLE
Introduction - Additional wording - Manual

### ISSUE THREAD

**Issue by bakkenb** [w3c/wai-eval-report-templates#4]
Priority: Medium
Location: Introduction - suggested update (highlighted yellow)
Current Wording:

> Note that you can also use the evaluation report tool generator, an interactive tool that leads you through an accessibility evaluation, to create an accessibility report based on the WCAG Evaluation Methodology.

Suggested Revision:

> Note that you can also use the evaluation report tool generator, an interactive tool that leads you through <b>a manual</b> accessibility evaluation, to create an accessibility report based on the WCAG Evaluation Methodology.

Rationale: Don't want users to think that the report tool generator is an automated accessibility checker tool as well.

**Comment by James-Green** [comment]
+1

**Comment by hkramer** [comment]
Incorporated Brent's suggestion.
