### ISSUE TITLE
HTML is bad

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-eval-report-templates#8]
e.g., missing `<p>`s

I fixed it in https://www.w3.org/WAI/eval/template

I do ***not*** think we should bother fixing it in this repo version now, because I think it will change a lot anyway (I'm looking at you, Eric, mr-clean-things-up-guy! :-)

**Comment by remibetin** [comment]
I am closing this issue that seems obsolete: the resource is now using Markdown, and the rendered HTML is clean now (checked with the [Markup Validation Service](https://validator.w3.org/))
